# Generated by Django 5.2.17 on 2026-08-11 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheckpointCaptura",
            fields=[
                (
                    "realm",
                    models.CharField(
                        max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("ultimo_timestamp", models.BigIntegerField(default=0)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Checkpoint de captura",
                "verbose_name_plural": "Checkpoints de captura",
            },
        ),
        migrations.CreateModel(
            name="EventoAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "evento_id_origem",
                    models.CharField(db_index=True, max_length=64),
                ),
                (
                    "tipo_evento",
                    models.CharField(db_index=True, max_length=50),
                ),
                (
                    "usuario_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("realm", models.CharField(max_length=100)),
                (
                    "client_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ip_origem",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                ("timestamp_evento", models.DateTimeField(db_index=True)),
                (
                    "timestamp_recebimento",
                    models.DateTimeField(auto_now_add=True),
                ),
                ("detalhes", models.JSONField(default=dict)),
            ],
            options={
                "verbose_name": "Evento de auditoria",
                "verbose_name_plural": "Eventos de auditoria",
                "indexes": [
                    models.Index(
                        fields=["usuario_id", "timestamp_evento"],
                        name="auditoria_e_usuario_e1dae7_idx",
                    ),
                    models.Index(
                        fields=["client_id", "timestamp_evento"],
                        name="auditoria_e_client__acdfad_idx",
                    ),
                    models.Index(
                        fields=["tipo_evento", "timestamp_evento"],
                        name="auditoria_e_tipo_ev_2e0758_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("evento_id_origem",),
                        name="uniq_evento_auditoria_origem",
                    )
                ],
            },
        ),
    ]
