# Generated by Django 5.2.17 on 2026-08-12 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auditoria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkpointcaptura",
            name="canal",
            field=models.CharField(default="usuario", max_length=20),
        ),
        # realm precisa deixar de ser a PK antes de id ser criado como
        # PK nova — o Postgres não aceita duas primary keys
        # simultâneas na mesma tabela, mesmo que a segunda operação
        # substitua a primeira dentro da mesma migration.
        migrations.AlterField(
            model_name="checkpointcaptura",
            name="realm",
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name="checkpointcaptura",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AddConstraint(
            model_name="checkpointcaptura",
            constraint=models.UniqueConstraint(
                fields=("realm", "canal"),
                name="uniq_checkpoint_captura_realm_canal",
            ),
        ),
    ]
