# Generated by Django 5.2.15 on 2026-09-21 16:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "auditoria",
            "0002_checkpointcaptura_canal_checkpointcaptura_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentificadorUsuarioAuditoria",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("usuario_id", models.CharField(db_index=True, max_length=64)),
                ("realm", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("EMAIL", "E-mail"),
                            ("CPF", "CPF"),
                            ("RF", "RF"),
                        ],
                        max_length=10,
                    ),
                ),
                ("valor", models.CharField(max_length=255)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Identificador de usuário de auditoria",
                "verbose_name_plural": "Identificadores de usuários de auditoria",
                "indexes": [
                    models.Index(
                        fields=["realm", "tipo", "valor"],
                        name="idx_ident_auditoria_busca",
                    ),
                    models.Index(
                        fields=["realm", "usuario_id"],
                        name="idx_ident_auditoria_usuario",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("realm", "usuario_id", "tipo", "valor"),
                        name="uniq_identificador_usuario_auditoria",
                    )
                ],
            },
        ),
    ]
